trigger:
  branches:
    include:
    - master
    - develop

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

stages:

- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: 'Build'
    displayName: 'Build & Publish Artifacts'
    variables:
    - group: 'Common'
    steps:
    - template: Build/build.yml

- stage: 'Release' 
  displayName: 'Release to Live'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: ['Build']
  jobs:
  - deployment: 'Appplication'
    displayName: 'Api & UI deployment'
    environment: 'Live'
    variables:
    - group: 'Common'
    - group: 'Live'
    strategy: 
      runOnce:
        deploy:               
          steps:
          - template: Build/release.yml
            parameters:
              serviceConnection: 'CAH-Connection'